### ISSUE TITLE
Is there a parameter to limit the number of variables in ITEA_regressor() bestsol_ output?

### ISSUE THREAD

**Issue by Rafail-Karkanis** [gAldeia/itea-python#6]
After executing ITEA on a dataset with a huge number of characteristics (approximately 20,000 columns), the resulting symbolic expression is excessively large and impractical for human interpretation.

Is dimensionality reduction before running ITEA_regressor() the only viable solution in such scenarios,
or is there a parameter within the ITEA_regressor() function that can constrain the number of variables in bestsol_?
Upon reviewing the documentation, I couldn't find such a parameter.

Thank you in advance.

**Comment by gAldeia** [comment]
Hello @Rafail-Karkanis ,

I apologize for the delay; I have been through busy days.

You are using many features, and I can see how limiting the maximum number of variables would help, but my implementation does not support this feature (in fact, I would love to do a multi-objective version of ITEA in the future when I have the time). 

Here are some alternatives you can try:
- Limit the number of terms with `max_terms`;
- Perform a feature selection with linear models and L1 regularization (aka Lasso) with scikit learn;
- Use [SelectKBest](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html) from sklearn as an alternative way of doing feature selection.

If none of the above can help get more interpretable solutions, then I suggest taking a look at my supervisor's (@folivetti) [implementation of ITEA](https://github.com/folivetti/ITEA). It is implemented in Haskell and has a Python wrapper with the following parameters:
- `termlimit`: a tuple of int representing the minimum and maximum number of terms in an expression
- `nonzeroexps` : number of non-zero exponents in each term of the initial population

You can install it on any Linux distribution.

Please let me know if this solves your problems!

**Comment by Rafail-Karkanis** [comment]
Dear Guilherme,

all the options were helpful for me and my issue is solved.
Per your suggestion, SelectKBest with score_func=f_regression,
along with some tinkering with the `max_terms` did the trick for me.

Thanks a lot for your work and answers.

Wishing you the best!
